### ISSUE TITLE
Packaging & documentation issues

### ISSUE THREAD

**Issue by konsumer** [Reynau/tiled-to-pixi#2]
Hi,
The docs say this:

```js
const TiledMap = require('TiledMap')
```

But your package is published as `tiled-to-pixi`, since the npm-published version of the lib is named that. In your package.json, main points to index.js (a non-existent file.) So with the current setup, the instructions should be this:

```js
const TiledMap = require('tiled-to-pixi/src/TiledMap')
```

But I'd recommend setting your main to `src/TiledMap.js` instead so people can do this:

```js
const TiledMap = require('tiled-to-pixi')
```

It looks like you did this, but didn't publish it on npm or update the docs.

Additionally, I get an error about fs not existing in the browser.
<img width="598" alt="screen shot 2017-12-29 at 12 30 28 am" src="https://user-images.githubusercontent.com/83857/34432802-86aca680-ec2f-11e7-9db7-c8c7e8951a4c.png">

How do you use it? brfs + browserify, maybe? I am using [babel-plugin-static-fs](https://www.npmjs.com/package/babel-plugin-static-fs) in webpack. I additionally get this error, which generally means there is some code trying to dynamically do something fancy with `fs`:

<img width="594" alt="screen shot 2017-12-29 at 1 05 55 am" src="https://user-images.githubusercontent.com/83857/34433475-80868334-ec34-11e7-9f81-c5da37ee2d4c.png">

**Comment by Reynau** [comment]
Solved. 
The way I use it is using browserify to generate a single js file (bundle.js). I added two examples where you can see it.
