### ISSUE TITLE
Pixi v5

### ISSUE THREAD

**Issue by toastal** [Reynau/tiled-to-pixi#4]
Pixi is already at 5.0.0-rc2. Are you planning to upgrade?

**Comment by Reynau** [comment]
Sure I will. But I will not be able to do it until the end of the month.

**Comment by axaq** [comment]
hey man. any news on this?

**Comment by axaq** [comment]
Btw, I just send a pull request with v5 support.

**Comment by Reynau** [comment]
Already got upgraded to Pixi v5
